# Compiler and Flags
CXX      := g++
CXXFLAGS := -std=c++20 -Wall -Wextra -Isrc -O3
LDFLAGS  := 

# Directories
SRC_DIR  := src
OBJ_DIR  := obj
BIN_DIR  := bin
TEST_DIR := test

# Find all .cpp files recursively in src/
SOURCES  := $(shell find $(SRC_DIR) -name "*.cpp")
# Map source files to object files in the obj/ directory
OBJECTS  := $(SOURCES:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%.o)
# Dependency files (generated by g++ -MMD)
DEPS     := $(OBJECTS:.o=.d)

# Target executable name
TARGET   := $(BIN_DIR)/compiler

.PHONY: all clean run test setup

# Default rule
all: setup $(TARGET)

# Create necessary directories
setup:
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	@mkdir -p $(dir $(OBJECTS))

# Link the executable
$(TARGET): $(OBJECTS)
	$(CXX) $(OBJECTS) -o $@ $(LDFLAGS)
	@echo "Build successful: $(TARGET)"

# Compile source files to object files
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -MMD -c $< -o $@

# Include dependency files if they exist
-include $(DEPS)

# Run the program
run: all
	@if [ -z "$(FILE)" ]; then \
		echo "Usage: make run FILE=<filename-in-test-input>"; \
		exit 1; \
	fi
	./$(TARGET) $(FILE)

# Clean build artifacts
clean:
	rm -rf $(OBJ_DIR) $(BIN_DIR)
	@echo "Cleaned up."

# Basic placeholder for tests
test: all
	@echo "Running tests..."
	@# Add your test execution command here
