# Compiler and Flags
CXX      := g++
CXXFLAGS := -std=c++20 -Wall -Wextra -Isrc -O3
LDFLAGS  := 

# Directories
SRC_DIR  := src
OBJ_DIR  := obj
BIN_DIR  := bin
TEST_DIR := test

# Find all .cpp files recursively in src/, excluding drivers
SOURCES  := $(shell find $(SRC_DIR) -name "*.cpp" ! -name "driver_*.cpp")
# Map source files to object files in the obj/ directory
OBJECTS  := $(SOURCES:$(SRC_DIR)/%.cpp=$(OBJ_DIR)/%.o)
# Dependency files (generated by g++ -MMD)
DEPS     := $(OBJECTS:.o=.d)

# Driver sources (separate from main compiler)
DRIVER_SRCS := $(shell find $(SRC_DIR) -name "driver_*.cpp")

# Target executable name
TARGET   := $(BIN_DIR)/compiler

# Driver executables
DRIVERS  := $(BIN_DIR)/driver_m1 $(BIN_DIR)/driver_m2 $(BIN_DIR)/driver_m3 $(BIN_DIR)/driver_m4

.PHONY: all clean run test setup drivers driver_m4 test-m4 test-m4-all

# Default rule
all: setup $(TARGET)

# Create necessary directories
setup:
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)
	@mkdir -p $(dir $(OBJECTS))

# Link the executable
$(TARGET): $(OBJECTS)
	$(CXX) $(OBJECTS) -o $@ $(LDFLAGS)
	@echo "Build successful: $(TARGET)"

# Compile source files to object files
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -MMD -c $< -o $@

# Include dependency files if they exist
-include $(DEPS)

# Run the program
run: all
	@if [ -z "$(FILE)" ]; then \
		echo "Usage: make run FILE=<filename-in-test-input>"; \
		exit 1; \
	fi
	./$(TARGET) $(FILE)

# Clean build artifacts
clean:
	rm -rf $(OBJ_DIR) $(BIN_DIR)
	@echo "Cleaned up."

# Build and run symbol table test
test-symbol-table:
	@echo "Building symbol table test..."
	@mkdir -p $(BIN_DIR)
	$(CXX) $(CXXFLAGS) test/test_symbol_table.cpp \
		src/semantic/TypeSystem.cpp \
		src/semantic/SymbolTableManager.cpp \
		-o $(BIN_DIR)/test_symbol_table
	@echo "Running symbol table test..."
	./$(BIN_DIR)/test_symbol_table

# Role 3 unit test
test-role3:
	$(CXX) $(CXXFLAGS) test/test_role3.cpp \
		src/runtime/StackMachine.cpp \
		src/runtime/Interpreter.cpp \
		src/intermediate/Instruction.cpp \
		-o $(BIN_DIR)/test_role3
	@echo "Running Role 3 unit tests..."
	$(BIN_DIR)/test_role3

# Basic placeholder for tests
test: all
	@echo "Running tests..."
	@# Add your test execution command here

# Build all milestone drivers
drivers: setup $(DRIVERS)
	@echo "All drivers built successfully"

# Driver M1: Lexical Analysis only
$(BIN_DIR)/driver_m1: $(SRC_DIR)/driver_m1.cpp $(OBJ_DIR)/lexical/Scanner.o $(OBJ_DIR)/lexical/Token.o $(OBJ_DIR)/lexical/SourceBuffer.o
	$(CXX) $(CXXFLAGS) $^ -o $@
	@echo "Built: $@"

# Driver M2: Syntax Analysis
$(BIN_DIR)/driver_m2: $(SRC_DIR)/driver_m2.cpp $(OBJ_DIR)/lexical/Scanner.o $(OBJ_DIR)/lexical/Token.o $(OBJ_DIR)/lexical/SourceBuffer.o $(OBJ_DIR)/syntax/Parser.o
	$(CXX) $(CXXFLAGS) $^ -o $@
	@echo "Built: $@"

# Driver M3: Semantic Analysis
$(BIN_DIR)/driver_m3: $(SRC_DIR)/driver_m3.cpp $(OBJ_DIR)/lexical/Scanner.o $(OBJ_DIR)/lexical/Token.o $(OBJ_DIR)/lexical/SourceBuffer.o $(OBJ_DIR)/syntax/Parser.o $(OBJ_DIR)/semantic/ParseTreeToAST.o $(OBJ_DIR)/semantic/SymbolTableManager.o $(OBJ_DIR)/semantic/TypeSystem.o $(OBJ_DIR)/semantic/SemanticAnalyzer.o
	$(CXX) $(CXXFLAGS) $^ -o $@
	@echo "Built: $@"

# Run individual drivers
test-m1: drivers
	@if [ -z "$(FILE)" ]; then \
		echo "Usage: make test-m1 FILE=<filename>"; \
		exit 1; \
	fi
	./$(BIN_DIR)/driver_m1 $(FILE)

test-m2: drivers
	@if [ -z "$(FILE)" ]; then \
		echo "Usage: make test-m2 FILE=<filename>"; \
		exit 1; \
	fi
	./$(BIN_DIR)/driver_m2 $(FILE)

test-m3: drivers
	@if [ -z "$(FILE)" ]; then \
		echo "Usage: make test-m3 FILE=<filename>"; \
		exit 1; \
	fi
	./$(BIN_DIR)/driver_m3 $(FILE)

# Convenience alias for driver_m4
driver_m4: $(BIN_DIR)/driver_m4

# Driver M4: Intermediate Code Generation & Interpreter
$(BIN_DIR)/driver_m4: $(SRC_DIR)/driver_m4.cpp $(OBJ_DIR)/lexical/Scanner.o $(OBJ_DIR)/lexical/Token.o $(OBJ_DIR)/lexical/SourceBuffer.o $(OBJ_DIR)/syntax/Parser.o $(OBJ_DIR)/semantic/ParseTreeToAST.o $(OBJ_DIR)/semantic/SymbolTableManager.o $(OBJ_DIR)/semantic/TypeSystem.o $(OBJ_DIR)/semantic/SemanticAnalyzer.o $(OBJ_DIR)/intermediate/CodeGenerator.o $(OBJ_DIR)/intermediate/Instruction.o $(OBJ_DIR)/runtime/StackMachine.o $(OBJ_DIR)/runtime/Interpreter.o
	$(CXX) $(CXXFLAGS) $^ -o $@
	@echo "Built: $@"

test-m4: drivers
	@if [ -z "$(FILE)" ]; then \
		echo "Usage: make test-m4 FILE=<filename>"; \
		exit 1; \
	fi
	./$(BIN_DIR)/driver_m4 $(FILE)

test-m4-all: drivers
	@echo "Running all M4 test cases..."
	@for f in test/milestone4/input/*.txt; do \
		echo "\n=== Testing $$(basename $$f) ==="; \
		./$(BIN_DIR)/driver_m4 $$(basename $$f); \
	done
